# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 2%
    patch:
      default:
        target: 90%
        # Allow 30% threshold for PRs that add integration-level code
        # in SubprocessTransport.Connect() which can't be unit tested
        # without a real Claude CLI binary
        threshold: 30%

ignore:
  - "examples/**/*"
